### ISSUE TITLE
Перестал работать перевод

### ISSUE THREAD

**Issue by Waiker** [FOSWLY/vot-cli#21]
Использую команду `vot-cli --output="." "https://disk.yandex.ru/i/ctRmuRBXwZoqqw"`

Скриптом пользовался последний раз 2 недели назад, проблем не было.

```
Translating finished! (ID: ctRmuRBXwZoqqw).
  ✔ Forming a link to the video
  ✔ Failed to request video translation
  ✖ Downloading failed! Link "Failed to request video translation" not found
  ✔ Finish (ID: ctRmuRBXwZoqqw).

AxiosError: Request failed with status code 400
    at settle (file:///usr/lib/node_modules/vot-cli/node_modules/axios/lib/core/settle.js:19:12)
    at IncomingMessage.handleStreamEnd (file:///usr/lib/node_modules/vot-cli/node_modules/axios/lib/adapters/http.js:589:11)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1400:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (file:///usr/lib/node_modules/vot-cli/node_modules/axios/lib/core/Axios.js:45:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async yandexRawRequest (file:///usr/lib/node_modules/vot-cli/src/yandexRawRequest.js:13:3)
    at async Object.requestVideoTranslation (file:///usr/lib/node_modules/vot-cli/src/yandexRequests.js:28:5)
    at async translateVideo (file:///usr/lib/node_modules/vot-cli/src/translateVideo.js:14:3)
    at async translate (file:///usr/lib/node_modules/vot-cli/src/index.js:93:5)
    at async file:///usr/lib/node_modules/vot-cli/src/index.js:281:32 {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/x-protobuf',
      'Content-Type': 'application/x-protobuf',
      'Accept-Language': 'en',
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 YaBrowser/24.1.0.0 Safari/537.36',
      Pragma: 'no-cache',
      'Cache-Control': 'no-cache',
      'Sec-Fetch-Mode': 'no-cors',
      'sec-ch-ua': null,
      'sec-ch-ua-mobile': null,
      'sec-ch-ua-platform': null,
      'Vtrans-Signature': '3b680fdba9d39d5285e288bcd2c25045075d7207ac89a3a281bf09a110772bb2',
      'Sec-Vtrans-Token': '5C0E3DE0779344558F2B74A17539542F',
      'Content-Length': '74',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    url: 'https://api.browser.yandex.ru/video-translation/translate',
    method: 'post',
    proxy: false,
    responseType: 'arraybuffer',
    data: <Buffer 1a 27 68 74 74 70 73 3a 2f 2f 64 69 73 6b 2e 79 61 6e 64 65 78 2e 72 75 2f 69 2f 63 74 52 6d 75 52 42 58 77 5a 6f 71 71 77 28 01 31 00 00 00 00 00 50 ... 24 more bytes>
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      finish: [Function: requestOnFinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    strictContentLength: false,
    _contentLength: '74',
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'api.browser.yandex.ru',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api.browser.yandex.ru',
      _closeAfterHandlingError: false,
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(alpncallback)]: null,
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 519,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: true,
      [Symbol(kSetKeepAliveInitialDelay)]: 60,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'POST /video-translation/translate HTTP/1.1\r\n' +
      'Accept: application/x-protobuf\r\n' +
      'Content-Type: application/x-protobuf\r\n' +
      'Accept-Language: en\r\n' +
      'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 YaBrowser/24.1.0.0 Safari/537.36\r\n' +
      'Pragma: no-cache\r\n' +
      'Cache-Control: no-cache\r\n' +
      'Sec-Fetch-Mode: no-cors\r\n' +
      'Vtrans-Signature: 3b680fdba9d39d5285e288bcd2c25045075d7207ac89a3a281bf09a110772bb2\r\n' +
      'Sec-Vtrans-Token: 5C0E3DE0779344558F2B74A17539542F\r\n' +
      'Content-Length: 74\r\n' +
      'Accept-Encoding: gzip, compress, deflate, br\r\n' +
      'Host: api.browser.yandex.ru\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    joinDuplicateHeaders: undefined,
    path: '/video-translation/translate',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 400,
      statusMessage: 'Bad Request',
      client: [TLSSocket],
      _consuming: true,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://api.browser.yandex.ru/video-translation/translate',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 18,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'api.browser.yandex.ru',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 74,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://api.browser.yandex.ru/video-translation/translate',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      'accept-language': [Array],
      'user-agent': [Array],
      pragma: [Array],
      'cache-control': [Array],
      'sec-fetch-mode': [Array],
      'vtrans-signature': [Array],
      'sec-vtrans-token': [Array],
      'content-length': [Array],
      'accept-encoding': [Array],
      host: [Array]
    },
    [Symbol(errored)]: null,
    [Symbol(kHighWaterMark)]: 16384,
    [Symbol(kRejectNonStandardBodyWrites)]: false,
    [Symbol(kUniqueHeaders)]: null
  },
  response: {
    status: 400,
    statusText: 'Bad Request',
    headers: Object [AxiosHeaders] {
      connection: 'Close',
      'content-length': '90',
      'content-type': 'text/plain; charset=utf-8',
      date: 'Sun, 26 May 2024 18:53:09 GMT',
      'set-cookie': [Array],
      'x-yandex-req-id': '1716749589785572-14494419283657589481-y2oxh7ayza6lstno-BAL'
    },
    config: {
      transitional: [Object],
      adapter: [Array],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object [AxiosHeaders]],
      url: 'https://api.browser.yandex.ru/video-translation/translate',
      method: 'post',
      proxy: false,
      responseType: 'arraybuffer',
      data: <Buffer 1a 27 68 74 74 70 73 3a 2f 2f 64 69 73 6b 2e 79 61 6e 64 65 78 2e 72 75 2f 69 2f 63 74 52 6d 75 52 42 58 77 5a 6f 71 71 77 28 01 31 00 00 00 00 00 50 ... 24 more bytes>
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '74',
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'POST /video-translation/translate HTTP/1.1\r\n' +
        'Accept: application/x-protobuf\r\n' +
        'Content-Type: application/x-protobuf\r\n' +
        'Accept-Language: en\r\n' +
        'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 YaBrowser/24.1.0.0 Safari/537.36\r\n' +
        'Pragma: no-cache\r\n' +
        'Cache-Control: no-cache\r\n' +
        'Sec-Fetch-Mode: no-cors\r\n' +
        'Vtrans-Signature: 3b680fdba9d39d5285e288bcd2c25045075d7207ac89a3a281bf09a110772bb2\r\n' +
        'Sec-Vtrans-Token: 5C0E3DE0779344558F2B74A17539542F\r\n' +
        'Content-Length: 74\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: api.browser.yandex.ru\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/video-translation/translate',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.browser.yandex.ru',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    data: <Buffer 28 65 72 72 6f 72 5f 69 64 3a 31 37 31 36 37 34 39 35 38 39 37 38 35 35 37 32 2d 31 34 34 39 34 34 31 39 32 38 33 36 35 37 35 38 39 34 38 31 2d 79 32 ... 40 more bytes>
  }
}
```

**Comment by Waiker** [comment]
Проблема решена обновлением
